export const ROUTES = {
	home: '/',
	login: '/login',
	register: '/register/:uuid',
	dashboard: '/dashboard',
	rooms: '/dashboard/rooms',
	room: '/dashboard/rooms/:roomId',
	plants: '/dashboard/plants',
	plant: '/dashboard/plants/:plantId',
	tasks: '/dashboard/tasks',
	task: '/dashboard/tasks/:taskId',
	record: '/dashboard/record/:recordId',
	reports: '/dashboard/reports',
	users: '/dashboard/users',
};
