export const TASKS_DATA = [
	{
		id: '1',
		description: 'Water the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '1',
		active: true,
		dateFinished: '2021-09-01',
	},
	{
		id: '2',
		description: 'Fertilize the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '2',
		active: false,
		dateFinished: '2021-09-01',
	},
	{
		id: '3',
		description: 'Prune the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '3',
		active: true,
		dateFinished: '2021-09-01',
	},
	{
		id: '4',
		description: 'Harvest the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '4',
		active: false,
		dateFinished: '2021-09-01',
	},
	{
		id: '5',
		description: 'Water the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '5',
		active: true,
		dateFinished: '2021-09-01',
	},
	{
		id: '6',
		description: 'Fertilize the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '6',
		active: false,
		dateFinished: '2021-09-01',
	},
	{
		id: '7',
		description: 'Prune the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '7',
		active: true,
		dateFinished: '2021-09-01',
	},
	{
		id: '8',
		description: 'Harvest the plant',
		assignedTo: 'John Doe',
		createdBy: 'Jane Doe',
		recordId: '8',
		active: false,
		dateFinished: '2021-09-01',
	},
];
